# -*- coding: utf-8 -*-
"""ITC4568_Final_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Us8YadWaBxj19il9toF0yS49fLHky8Vm

## Setup – Mount Drive or Upload Data
"""

import zipfile, os

ZIP_PATH = 'ITC4568 Final_Project_data.zip'
EXTRACT_DIR = 'project_data'
os.makedirs(EXTRACT_DIR, exist_ok=True)

with zipfile.ZipFile(ZIP_PATH, 'r') as z:
    z.extractall(EXTRACT_DIR)

print('Extracted files:')
for root, dirs, fnames in os.walk(EXTRACT_DIR):
    for f in fnames:
        print(os.path.join(root, f))

import os, glob, re
import numpy as np
import pandas as pd
from pathlib import Path

import warnings
warnings.filterwarnings('ignore')

"""---
# PART 1 – Preprocessing the Data

## Part 1A – Combine all raw CSV files into one
"""

LABEL_MAP = {
    'AllTapsClosed': 0,
    'Tap1Open':      1,
    'Tap2Open':      2,
    'Tap3Open':      3,
    'Tap4Open':      4,
}

def extract_label_from_filename(fname):

    base = Path(fname).stem
    option = base.split('_tag_')[-1]
    return LABEL_MAP.get(option, -1)


def build_all_data(root_dir, sensor_number):

    pattern = os.path.join(root_dir, '**', 'Leakage1_tag_*.csv')
    csv_files = sorted(glob.glob(pattern, recursive=True))

    if not csv_files:
        raise FileNotFoundError(f'No Leakage CSV files found under: {root_dir}')

    frames = []
    for fpath in csv_files:
        label = extract_label_from_filename(fpath)
        if label == -1:
            print(f'  WARNING: unknown label in {fpath}, skipping.')
            continue
        df = pd.read_csv(fpath, header=0, names=['timestamp', 'value'])
        df['label'] = label
        frames.append(df)
        print(f'  Read {len(df):,} rows  label={label}  from {fpath}')

    all_data = pd.concat(frames, ignore_index=True)
    all_data.sort_values('timestamp', inplace=True)
    all_data.reset_index(drop=True, inplace=True)

    out_file = f'ALL_DATA_{sensor_number}.csv'
    all_data.to_csv(out_file, index=False)
    print(f'\nSaved {len(all_data):,} total rows → {out_file}')
    return all_data, out_file



def find_sensor_dir(base, sensor_num):

    for entry in os.listdir(base):

        if f'Sensor{sensor_num}' in entry and 'Leakage' in entry and os.path.isdir(os.path.join(base, entry)):
            return os.path.join(base, entry)
    return base

BASE = EXTRACT_DIR

sensor1_dir = find_sensor_dir(BASE, 1)
print(f'Sensor1 directory: {sensor1_dir}')
all_data_1, f1 = build_all_data(sensor1_dir, 1)

sensor2_dir = find_sensor_dir(BASE, 2)
print(f'\nSensor2 directory: {sensor2_dir}')
all_data_2, f2 = build_all_data(sensor2_dir, 2)

print('=== ALL_DATA_1 ===' )
print(all_data_1.head())
print(all_data_1['label'].value_counts().sort_index())

print('\n=== ALL_DATA_2 ===')
print(all_data_2.head())
print(all_data_2['label'].value_counts().sort_index())

"""## Part 1B – Aggregate into 0.1-second windows



"""

WINDOW = 0.1

def aggregate_data(all_data_df, sensor_number):

    rows = all_data_df[['timestamp', 'value', 'label']].values

    aggr_rows = []

    bucket_start_ts   = rows[0, 0]
    bucket_label      = int(rows[0, 2])
    bucket_values     = [rows[0, 1]]

    def flush_bucket(ts, vals, lbl):
        aggr_rows.append({
            'ts':            ts,
            'average_value': float(np.mean(vals)),
            'min_value':     float(np.min(vals)),
            'max_value':     float(np.max(vals)),
            'label':         lbl,
        })

    for i in range(1, len(rows)):
        ts    = rows[i, 0]
        val   = rows[i, 1]
        label = int(rows[i, 2])

        if label != bucket_label or (ts - bucket_start_ts) > WINDOW:
            flush_bucket(bucket_start_ts, bucket_values, bucket_label)

            bucket_start_ts = ts
            bucket_label    = label
            bucket_values   = [val]
        else:
            bucket_values.append(val)

    flush_bucket(bucket_start_ts, bucket_values, bucket_label)

    aggr_df = pd.DataFrame(aggr_rows,
                           columns=['ts','average_value','min_value','max_value','label'])

    out_file = f'AGGR_DATA_{sensor_number}.csv'
    aggr_df.to_csv(out_file, index=False)
    print(f'Saved {len(aggr_df):,} aggregated rows → {out_file}')
    return aggr_df


aggr1 = aggregate_data(all_data_1, 1)
aggr2 = aggregate_data(all_data_2, 2)

print('\nAGGR_DATA_1 sample:')
print(aggr1.head())
print('\nAGGR_DATA_2 sample:')
print(aggr2.head())

"""## Part 1C – Merge Sensor 1 & Sensor 2"""

def merge_aggr(aggr1_df, aggr2_df):

    a1 = aggr1_df.copy().reset_index(drop=True)
    a2 = aggr2_df.copy().reset_index(drop=True)

    merged_rows = []


    a2_ts   = a2['ts'].values
    a2_end  = a2_ts + WINDOW

    def find_overlapping_s2(ts):

        row_end = ts + WINDOW

        mask = (a2_ts < row_end) & (a2_end > ts)
        return np.where(mask)[0]

    used_s2 = set()


    for _, r1 in a1.iterrows():
        ts    = r1['ts']
        s2_idx = find_overlapping_s2(ts)

        if len(s2_idx) == 0:

            merged_rows.append({
                'ts':     ts,
                's1_avg': r1['average_value'],
                's1_min': r1['min_value'],
                's1_max': r1['max_value'],
                's2_avg': np.nan,
                's2_min': np.nan,
                's2_max': np.nan,
                'label':  r1['label'],
            })
        else:

            s2_sub = a2.iloc[s2_idx]
            merged_rows.append({
                'ts':     ts,
                's1_avg': r1['average_value'],
                's1_min': r1['min_value'],
                's1_max': r1['max_value'],
                's2_avg': s2_sub['average_value'].mean(),
                's2_min': s2_sub['min_value'].min(),
                's2_max': s2_sub['max_value'].max(),
                'label':  r1['label'],
            })
            used_s2.update(s2_idx.tolist())

    for i, r2 in a2.iterrows():
        if i in used_s2:
            continue
        merged_rows.append({
            'ts':     r2['ts'],
            's1_avg': np.nan,
            's1_min': np.nan,
            's1_max': np.nan,
            's2_avg': r2['average_value'],
            's2_min': r2['min_value'],
            's2_max': r2['max_value'],
            'label':  r2['label'],
        })

    merged_df = pd.DataFrame(merged_rows,
        columns=['ts','s1_avg','s1_min','s1_max','s2_avg','s2_min','s2_max','label'])
    merged_df.sort_values('ts', inplace=True)
    merged_df.reset_index(drop=True, inplace=True)

    merged_df.to_csv('AGGR_DATA_ALL.csv', index=False)
    print(f'Saved {len(merged_df):,} merged rows → AGGR_DATA_ALL.csv')
    return merged_df


merged_df = merge_aggr(aggr1, aggr2)
print(merged_df.head(10))
print('\nMissing values per column:')
print(merged_df.isna().sum())
print('\nLabel distribution:')
print(merged_df['label'].value_counts().sort_index())

"""---
# PART 2 – Training ML Models

## Prepare the Feature Matrix
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, f1_score, classification_report

df = pd.read_csv('AGGR_DATA_ALL.csv')


X_raw = df.drop(columns=['ts', 'label']).values
y     = df['label'].values.astype(int)


imputer = SimpleImputer(strategy='mean')
X_imp   = imputer.fit_transform(X_raw)

scaler = StandardScaler()
X_sc   = scaler.fit_transform(X_imp)


X_train, X_temp, y_train, y_temp = train_test_split(
    X_sc, y, test_size=0.60, random_state=42, stratify=y)


X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp)

print(f'Training set  : {X_train.shape}')
print(f'Validation set: {X_val.shape}')
print(f'Test set      : {X_test.shape}')
print(f'\nFeatures: {X_sc.shape[1]}   Classes: {np.unique(y)}')

"""## Part 2A - MLPClassifier"""

from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(
    hidden_layer_sizes=(10,),
    activation='relu',
    solver='adam',
    learning_rate_init=0.001,
    max_iter=500,
    random_state=42,
)

# Trainingv
mlp.fit(X_train, y_train)

# Evaluation
y_val_pred  = mlp.predict(X_val)
val_acc     = accuracy_score(y_val, y_val_pred)
val_f1      = f1_score(y_val, y_val_pred, average='weighted')

y_test_pred = mlp.predict(X_test)
test_acc    = accuracy_score(y_test, y_test_pred)
test_f1     = f1_score(y_test, y_test_pred, average='weighted')

print('=== Shallow Neural Network Results ===')
print(f'Validation  Accuracy: {val_acc:.4f}   F1 (weighted): {val_f1:.4f}')
print(f'Test        Accuracy: {test_acc:.4f}   F1 (weighted): {test_f1:.4f}')
print('\nDetailed Test Report:')
print(classification_report(y_test, y_test_pred,
      target_names=['AllTapsClosed','Tap1Open','Tap2Open','Tap3Open','Tap4Open']))

"""## Part 2A – Decision Tree


"""

from sklearn.tree import DecisionTreeClassifier


X_eval = np.vstack([X_val,  X_test])
y_eval = np.concatenate([y_val, y_test])

dt = DecisionTreeClassifier(random_state=42, max_depth=None)
dt.fit(X_train, y_train)

y_eval_pred = dt.predict(X_eval)
dt_acc      = accuracy_score(y_eval, y_eval_pred)
dt_f1       = f1_score(y_eval, y_eval_pred, average='weighted')

print('=== Decision Tree Results ===')
print(f'Eval Accuracy: {dt_acc:.4f}   F1 (weighted): {dt_f1:.4f}')
print('\nDetailed Eval Report:')
print(classification_report(y_eval, y_eval_pred,
      target_names=['AllTapsClosed','Tap1Open','Tap2Open','Tap3Open','Tap4Open']))

print(f'\nTree depth: {dt.get_depth()}   Leaves: {dt.get_n_leaves()}')

"""---
# PART 3 – Improving the Results

## Part 3A - Rolling Max Absolute Value
"""

df_aug = pd.read_csv('AGGR_DATA_ALL.csv')

# Feature 1
LOOKBACK = 10.0

ts_vals     = df_aug['ts'].values
s1_avg_vals = df_aug['s1_avg'].fillna(0).values
s2_avg_vals = df_aug['s2_avg'].fillna(0).values

max_abs_10s_s1 = np.zeros(len(df_aug))
max_abs_10s_s2 = np.zeros(len(df_aug))

for i in range(len(df_aug)):
    window_mask = (ts_vals >= ts_vals[i] - LOOKBACK) & (ts_vals <= ts_vals[i])
    max_abs_10s_s1[i] = np.max(np.abs(s1_avg_vals[window_mask]))
    max_abs_10s_s2[i] = np.max(np.abs(s2_avg_vals[window_mask]))

df_aug['max_abs_10s_s1'] = max_abs_10s_s1
df_aug['max_abs_10s_s2'] = max_abs_10s_s2

#  spread of vibration
df_aug['s1_range'] = df_aug['s1_max'].fillna(0) - df_aug['s1_min'].fillna(0)
df_aug['s2_range'] = df_aug['s2_max'].fillna(0) - df_aug['s2_min'].fillna(0)

df_aug.to_csv('AGGR_DATA_ALL_AUG.csv', index=False)
print(f'Augmented dataset shape: {df_aug.shape}')
print(df_aug.head())

X_aug_raw = df_aug.drop(columns=['ts','label']).values
y_aug     = df_aug['label'].values.astype(int)

imp2    = SimpleImputer(strategy='mean')
X_aug_i = imp2.fit_transform(X_aug_raw)

sc2     = StandardScaler()
X_aug_s = sc2.fit_transform(X_aug_i)

Xtr, Xtmp, ytr, ytmp = train_test_split(X_aug_s, y_aug, test_size=0.60,
                                         random_state=42, stratify=y_aug)
Xv, Xte, yv, yte     = train_test_split(Xtmp, ytmp, test_size=0.50,
                                         random_state=42, stratify=ytmp)

#  MLP
mlp2 = MLPClassifier(hidden_layer_sizes=(10,), activation='relu',
                     solver='adam', max_iter=500, random_state=42)
mlp2.fit(Xtr, ytr)

aug_mlp_acc = accuracy_score(yte, mlp2.predict(Xte))
aug_mlp_f1  = f1_score(yte, mlp2.predict(Xte), average='weighted')

#  Decision Tree
Xeval2 = np.vstack([Xv, Xte])
yeval2 = np.concatenate([yv, yte])

dt2 = DecisionTreeClassifier(random_state=42)
dt2.fit(Xtr, ytr)
aug_dt_acc = accuracy_score(yeval2, dt2.predict(Xeval2))
aug_dt_f1  = f1_score(yeval2, dt2.predict(Xeval2), average='weighted')

print(f'MLP  Test Accuracy: {aug_mlp_acc:.4f}   F1: {aug_mlp_f1:.4f}')
print(f'DT   Eval Accuracy: {aug_dt_acc:.4f}   F1: {aug_dt_f1:.4f}')

"""## Part 3B - Neural Network Topologies + CNN

"""

# Deeper MLP
mlp_deep = MLPClassifier(
    hidden_layer_sizes=(64, 32, 16),
    activation='tanh',
    solver='adam',
    learning_rate='adaptive',
    max_iter=1000,
    random_state=42,
    alpha=0.01,
)
mlp_deep.fit(Xtr, ytr)

deep_acc = accuracy_score(yte, mlp_deep.predict(Xte))
deep_f1  = f1_score(yte, mlp_deep.predict(Xte), average='weighted')
print(f'Deep MLP (64→32→16, tanh)  Test Accuracy: {deep_acc:.4f}   F1: {deep_f1:.4f}')

"""### 3B-2:CNN
```
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

tf.random.set_seed(42)


n_features = Xtr.shape[1]
Xtr_cnn = Xtr.reshape(-1, n_features, 1)
Xv_cnn  = Xv.reshape(-1, n_features, 1)
Xte_cnn = Xte.reshape(-1, n_features, 1)

n_classes = 5
ytr_oh  = keras.utils.to_categorical(ytr,  n_classes)
yv_oh   = keras.utils.to_categorical(yv,   n_classes)
yte_oh  = keras.utils.to_categorical(yte,  n_classes)

# CNN model
cnn_model = keras.Sequential([
    layers.Input(shape=(n_features, 1)),
    layers.Conv1D(32, kernel_size=3, activation='relu', padding='same'),
    layers.Conv1D(64, kernel_size=3, activation='relu', padding='same'),
    layers.GlobalMaxPooling1D(),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(n_classes, activation='softmax'),
])

cnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',   #
    metrics=['accuracy'],
)

cnn_model.summary()

# training
early_stop = keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=10, restore_best_weights=True)

history = cnn_model.fit(
    Xtr_cnn, ytr_oh,
    validation_data=(Xv_cnn, yv_oh),
    epochs=100,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1,
)

# Evaluation
cnn_loss, cnn_acc_raw = cnn_model.evaluate(Xte_cnn, yte_oh, verbose=0)
y_cnn_pred = np.argmax(cnn_model.predict(Xte_cnn), axis=1)
cnn_f1     = f1_score(yte, y_cnn_pred, average='weighted')

print(f'\nCNN Test Accuracy: {cnn_acc_raw:.4f}   F1: {cnn_f1:.4f}')
print(classification_report(yte, y_cnn_pred,
      target_names=['AllTapsClosed','Tap1Open','Tap2Open','Tap3Open','Tap4Open']))

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].plot(history.history['accuracy'],     label='Train')
axes[0].plot(history.history['val_accuracy'], label='Val')
axes[0].set_title('CNN Accuracy')
axes[0].legend()

axes[1].plot(history.history['loss'],     label='Train')
axes[1].plot(history.history['val_loss'], label='Val')
axes[1].set_title('CNN Loss')
axes[1].legend()

plt.tight_layout()
plt.savefig('cnn_training_curves.png', dpi=150)
plt.show()